// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-1_OtgoM4NaqNAcTlWvSGOVtBXkW--ek',
    appId: '1:132095323619:web:61670f66be4c6ee802c4d6',
    messagingSenderId: '132095323619',
    projectId: 'workout-helper-7bda2',
    authDomain: 'workout-helper-7bda2.firebaseapp.com',
    storageBucket: 'workout-helper-7bda2.appspot.com',
    measurementId: 'G-TFSY8PWWX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUJY8MRZSsy4NputBWST-99l_uGunlxZA',
    appId: '1:132095323619:android:49179f46ba9292f802c4d6',
    messagingSenderId: '132095323619',
    projectId: 'workout-helper-7bda2',
    storageBucket: 'workout-helper-7bda2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtG1RL_5OaCI1OkHB9F1weOnJWW0ylE_U',
    appId: '1:132095323619:ios:81b9b610c9bc531a02c4d6',
    messagingSenderId: '132095323619',
    projectId: 'workout-helper-7bda2',
    storageBucket: 'workout-helper-7bda2.appspot.com',
    iosBundleId: 'com.decryptcode.workoutmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtG1RL_5OaCI1OkHB9F1weOnJWW0ylE_U',
    appId: '1:132095323619:ios:81b9b610c9bc531a02c4d6',
    messagingSenderId: '132095323619',
    projectId: 'workout-helper-7bda2',
    storageBucket: 'workout-helper-7bda2.appspot.com',
    iosBundleId: 'com.decryptcode.workoutmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-1_OtgoM4NaqNAcTlWvSGOVtBXkW--ek',
    appId: '1:132095323619:web:3b737ec77579189e02c4d6',
    messagingSenderId: '132095323619',
    projectId: 'workout-helper-7bda2',
    authDomain: 'workout-helper-7bda2.firebaseapp.com',
    storageBucket: 'workout-helper-7bda2.appspot.com',
    measurementId: 'G-J049ZPTKHF',
  );
}
